
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const FromWebsite = {
  UNKNOWN: 'UNKNOWN',
  REMOTEOK: 'REMOTEOK'
} as const

export type FromWebsite = (typeof FromWebsite)[keyof typeof FromWebsite]


export const ApplicationState = {
  POSTED: 'POSTED',
  REJECTED: 'REJECTED',
  ONGOING: 'ONGOING',
  FAILED: 'FAILED'
} as const

export type ApplicationState = (typeof ApplicationState)[keyof typeof ApplicationState]
